sudo: required
language: generic

services:
    -   docker

before_install:
    -   docker build -t andreasatle/docker-react -f Dockerfile.dev .

script:
    -   docker run -e CI=true andreasatle/docker-react npm run test