sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t andreasatle/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true andreasatle/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-356810367154"
    bucket-path: "docker-react-app"
    on:
        branch: master
    acces_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY